server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:department-service-db
    username: department_admin
    password: secret
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-sql: false
    show_sql: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true