server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:department_service_db
    username: department_admin
    password: secret
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show_sql: true
    hibernate:
      ddl-auto: validate
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # fix bug caused by interaction of springfox and spring boot
