server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: api/employee-service-api.yaml
